services:
  - type: web
    name: emotion-ai-buddy-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: HUGGINGFACE_API_KEY
        value: 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
    healthCheckPath: /auth/health
