services:
  - type: web
    name: emotion-ai-buddy-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: HUGGINGFACE_API_KEY
        value: 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
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
    healthCheckPath: /auth/health
