spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
huggingface.api.key=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
