spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always
huggingface.api.key=${HUGGINGFACE_API_KEY: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}
